image: codogo/pipelines-universal:latest

pipelines:
  branches:
    master:
      - step:
          script:
          - yarn install 
          - CI=false yarn run lint
          - CI=false yarn run build
          - aws s3 sync --delete build s3://codogo-app-muswell-press-marketing
